services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-inventory}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password123}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME:-inventory}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-password123}
    volumes:
      - .:/app

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: mysql+mysqldb://root:${DB_PASSWORD:-password123}@db:3306/${DB_NAME:-inventory}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./airflow:/opt/airflow/airflow
      - ./airflow/include:/opt/airflow/include
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true &&
               airflow webserver & airflow scheduler"

volumes:
  mysql_data:
